# Tender Rules Configuration

# Budget rules
budget:
  max_budget: 1000000  # Maximum budget in currency units
  currency: "USD"

# Timeline rules
timeline:
  max_duration_months: 24  # Maximum project duration in months

# Certification requirements
certifications:
  required:
    - "ISO 9001"
    - "ISO 14001"
  preferred:
    - "ISO 45001"
    - "CMMI"

# Technical requirements (used for semantic matching)
technical_requirements:
  - "Experience in software development"
  - "Knowledge of cloud platforms"
  - "Security compliance experience"
  - "Project management certification"

# Scoring weights for different evaluation criteria
scoring_weights:
  technical_compliance: 0.4
  budget_compliance: 0.3
  timeline_compliance: 0.2
  certification_compliance: 0.1

# Evaluation thresholds
evaluation_thresholds:
  minimum_score: 70  # Minimum score to be considered
  shortlist_count: 10  # Number of top applicants to shortlist