# Streamlit secrets file
# This file should be updated with actual values for deployment

[ollama]
base_url = "http://localhost:11434"

[paths]
org_documents = "./data/org_documents"
applicant_documents = "./data/applicant_documents"
output_reports = "./data/reports"